// Drive a MeshBench workbench from Node.
//
//   import { Workbench } from "@meshbench/client";
//
//   const wb = await Workbench.headless({ fixture: "fife-strict", seed: 9001 });
//   try {
//     await wb.sim.start();
//     await wb.sim.run(5 * 60_000);
//     console.log(String(await wb.provenance()));
//     console.log(await wb.events.total(), "events");
//   } finally {
//     await wb.close();
//   }
//
// Speaks the same control socket as pkg/client-go and pkg/client-python, on the
// same machine, and carries the same shape: `wb.nodes`, `wb.sim`,
// `wb.firmware`, `wb.events`, `wb.project`, `wb.live`, `wb.boundary` and a
// node's own console. Where the three differ it is because a language differs -
// a Python property that reads the session is a method here, because a method
// is what JavaScript has for something that awaits.
//
// Two layers, and both are public. `wb.call(verb, params)` is the whole
// protocol, so a verb this package has not shaped is one line away rather than
// a blocker; the shape above it is what a script should reach for first,
// because every helper on it exists to stop a mistake somebody has already
// made.
//
// Every wait is a method - `node.waitRunning()`, `sim.run()`,
// `firmware.waitStarted()` - never a sleep in a script. They poll today and
// will subscribe later, and no script changes when they do.
//
// A wait measured in simulated time is not a wait measured in yours:
// `sim.run(5 * 60_000)` is five minutes of the mesh's own clock, and on 155
// emulated nodes that is a great deal longer than five of yours. Nothing that
// means the mesh's clock is called a timeout.
//
// Zero dependencies and no build step: it is ES modules on Node's own `net`,
// because a client that needed a framework to speak to a local socket would be
// a client nobody could debug.

export { Workbench } from "./lib/workbench.mjs";

export {
  BadParams, Closing, Conflict, MeshbenchError, NotFound, ProtocolMismatch,
  Timeout, Unavailable, UnknownVerb, VersionMismatch, WorkbenchError,
} from "./lib/errors.mjs";

export { PROTOCOL, RELEASE, pairedRelease, pairingNote } from "./lib/pairing.mjs";

export {
  BINARY_ENV, DEFAULT_CALL_TIMEOUT_MS, MAX_UNIX_PATH, RENDEZVOUS_ENV,
  SESSIONS_ENV, SOCKET_ENV, defaultAddress,
} from "./lib/socket.mjs";

export { START_TIMEOUT_MS } from "./lib/launch.mjs";

export { DETAIL_WAIT_MS, sessions, sessionsDir } from "./lib/sessions.mjs";

export {
  EVENT_WAIT_MS, FIRMWARE_WAIT_MS, JOB_WAIT_MS, RUN_WAIT_MS,
} from "./lib/wait.mjs";

export { ImportPreview, Provenance, describeBuild } from "./lib/values.mjs";

export { ASSERTION_KINDS, Assertions, Check, Report, Schedule } from "./lib/checks.mjs";

export { Boundary } from "./lib/boundary.mjs";
export { DEFAULT_WINDOW_HOURS, Live } from "./lib/live.mjs";
export { FIND_LEAST, Node, Nodes } from "./lib/nodes.mjs";
export { Console, Events, Job, Project } from "./lib/parts.mjs";
export { Firmware } from "./lib/firmware.mjs";
export { Sim } from "./lib/sim.mjs";
export { SCREEN_WAIT_MS, Device } from "./lib/device.mjs";
export { SUBSCRIBE, Subscription } from "./lib/subscribe.mjs";

// The closed sets, generated by tools/clientgen from internal/world/scenario.
// Never spell one as a free string: a board name nothing matches produces a
// different node, silently.
export {
  Board, Boards, Class, Classes, DEFAULT_PRESET, Kind, Preset, Presets,
  Role, Roles, Strategy, Tab, Tabs, Transport,
} from "./lib/sets.mjs";
